CREATE TABLE IF NOT EXISTS Users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    passhash VARCHAR(255) NOT NULL,
    passalt VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS Identities (
    userId INT NOT NULL,
    identity VARCHAR(255) NOT NULL,
    PRIMARY KEY(userId, identity),
    FOREIGN KEY (userId) REFERENCES Users(id)
);